const INTERNAL_SERVER_ERROR = 500;
const LOCKED = 423;
const TOKEN_MISMATCH= 419;
const UNAUTHORIZED = 401;
const UNPROCESSABLE_ENTITY = 422;

export {
    INTERNAL_SERVER_ERROR,
    LOCKED,
    UNAUTHORIZED,
    UNPROCESSABLE_ENTITY,
    TOKEN_MISMATCH
}