declare const FORBIDDEN = 403;
declare const INTERNAL_SERVER_ERROR = 500;
declare const LOCKED = 423;
declare const TOKEN_MISMATCH = 419;
declare const UNAUTHORIZED = 401;
declare const UNPROCESSABLE_ENTITY = 422;
export { FORBIDDEN, INTERNAL_SERVER_ERROR, LOCKED, UNAUTHORIZED, UNPROCESSABLE_ENTITY, TOKEN_MISMATCH };
